### PR TITLE
contentInsets

### PR DESCRIPTION
**Pull request by avalanched**
property to set an inset on the text content.

### CODE REVIEW

**Comment by KyoheiG3** [comment]
The inset, I think I try to use `lineFragmentPadding` of `NSTextContainer`.
Thank you.

**Comment by KyoheiG3** [comment]
Fixed in https://github.com/KyoheiG3/AttributedLabel/commit/4e74151ec241def69c99ebbb04def4ab51ac6bac

**Comment by avalanched** [comment]
nice find, forgot about that :)

**Comment by avalanched** [comment]
on an other note do you want to add more convenience properties or do you want to keep it as simple as possible?

**Comment by KyoheiG3** [comment]
I want to more convenience. however, keep it as simple as possible. I think simple is best.

**Pull request closed without merging**
