### PR TITLE
Support autolayout intrinsicContentSize

### PR DESCRIPTION
**Pull request by fgengine**

### CODE REVIEW

**Comment by KyoheiG3** [comment]
Hi @fgengine 
It seems good but I guess `sizeThatFits` is not fast. I don't want to sacrifice layout performance.

**Comment by fgengine** [comment]
Hi @KyoheiG3
Perhaps the performance is not the biggest but the best to have support for automatic calculation of the size of than not to have, but is proud that works fast.

**Comment by KyoheiG3** [comment]
I think so. I want to use `sizeThatFit` only when necessary.
For example, to use some flags.

**Comment by KyoheiG3** [comment]
It was supported.
Please use `var intrinsicAutoLayout: Bool` and check README about the flag.

**Pull request closed without merging**
